---
title: "citi_ridership_pc_change"
output: html_document
---

```{r, load required packages, include = FALSE}
library(tidyverse)
library(lubridate)
library(plotly)

knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE
)
```

```{r, read in manhattan rides data}
manhattan_rides_df <- read_csv("manhattan_rides.csv")

manhattan_rides_df <-
  manhattan_rides_df %>% 
  mutate(
    day_of_week = factor(day_of_week, ordered = T, 
                         levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), 
    year = factor(year), 
    age_group = factor(age_group, ordered = T,
                       levels = c("18-25","26-35", "36-45", "46-55", "56-65", "66-85"))
  )

manhattan_rides_df %>% 
  group_by(age_group) %>% 
  summarize(min = min(age), max = max(age), obs = n())
```

```{r, percent change dataset}
citi_pc_change = 
  manhattan_rides_df %>% 
  mutate(date = format(stoptime, format = "%m-%d-%Y")) %>% 
  group_by(stop_date, year) %>% 
  summarize(daily_rides = n()) %>% 
  ungroup() %>% 
  group_by(stop_date) %>% 
  arrange(year, .by_group = T) %>% 
  mutate(percent_change = (daily_rides/lag(daily_rides) - 1) * 100) %>%
  filter(year == 2020) %>% 
  select(date = stop_date, percent_change) %>% 
  mutate(transit_system = "citi_bike",
         date = paste0("2020-", date),
         date = as.Date(date, "%Y-%m-%d"))
```



```{r, CitiBike ridership percent change plot}
# Using ggplot
post_covid_transit = citi_pc_change %>% 
  ungroup() %>% 
  drop_na() %>% 
  ggplot(aes(x = date, y = percent_change, color = transit_system)) +
  geom_smooth(aes(color = transit_system))

ggplotly(post_covid_transit)
```

```{r, copied from subway_rides RMD}
#Ridership data for 2019/2020 Manhattan
turnstiles_2019_m = read_csv("2019-turnstile.csv") %>% 
  filter(borough == "M") %>% 
  mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))
  
  
turnstiles_2020_m = read_csv("2020-turnstile.csv") %>% 
    filter(borough == "M") %>% 
    mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))

turnstiles_19_20_m = rbind(turnstiles_2019_m, turnstiles_2020_m)

#Ridership data 3/1/2020 - today
ridership_covid_changes = read_csv("covid-ridership.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, "%m/%d/%Y")) %>% 
  rename(buses_ter = buses_total_estimated_ridership) %>% 
  rename(lirr_ter = lirr_total_estimated_ridership) %>% 
  rename(metro_north_ter = metro_north_total_estimated_ridership) %>% 
  rename(subways_ter = subways_total_estimated_ridership) %>% 
  rename(subways_pc = subways_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(metro_north_pc = metro_north_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(lirr_pc = lirr_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(buses_pc = buses_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(bridges_and_tunnels_pc = bridges_and_tunnels_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(access_a_ride_ter = access_a_ride_total_scheduled_trips) %>% 
  rename(access_a_ride_pc = access_a_ride_percent_change_from_pre_pandemic_equivalent_day)


ridership_covid_changes_2020 = ridership_covid_changes %>% 
  filter(date <= as.Date('2020-12-31'))

ridership_covid_pc_tidy = 
  ridership_covid_changes_2020 %>% 
  
  select(date, access_a_ride_pc, bridges_and_tunnels_pc, buses_pc, lirr_pc, metro_north_pc, subways_pc) %>% 
  
  pivot_longer(
    c(access_a_ride_pc:subways_pc), 
    names_to = "transit_system",
    values_to = "percent_change"
  ) %>% 
  
   mutate(transit_system = gsub("_pc", "", transit_system),
          percent_change = gsub("%", "", percent_change),
          percent_change = as.numeric(percent_change))
```

```{r, Join datasets}
ridership_pc_change = 
  bind_rows(ridership_covid_pc_tidy, citi_pc_change)
```

```{r, plot with everything}
# Using ggplot
post_covid_transit = ridership_pc_change %>% 
  ungroup() %>% 
  drop_na() %>% 
  filter(date >= as.Date('2020-03-01')) %>% 
  ggplot(aes(x = date, y = percent_change, color = transit_system)) +
  geom_smooth(aes(color = transit_system))

ggplotly(post_covid_transit)

# Using plotly 
ridership_pc_change %>% 
  ungroup() %>% 
  drop_na() %>% 
  filter(date >= as.Date('2020-03-01')) %>% 
  plot_ly(
    x = ~date, 
    y = ~percent_change, 
    color = ~transit_system,
    type = "scatter",
    mode = "lines") %>% 
  layout(
    title = "Ridership Transit System Percent Change Following COVID",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Percent Change")
  )
```

