---
title: "P8105 Final Project: Citi Bikes"
output: github_document
---

```{r, load required packages, include = FALSE}
library(tidyverse)
library(lubridate)

knitr::opts_chunk$set(
  message = FALSE, 
  warning = FALSE
)
```

```{r, read in manhattan rides data}
manhattan_rides_df <- read_csv("manhattan_rides.csv")

manhattan_rides_df <-
  manhattan_rides_df %>% 
  mutate(
    day_of_week = factor(day_of_week, ordered = T, 
                         levels = c("Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat")), 
    year = factor(year), 
    age_group = factor(age_group, ordered = T,
                       levels = c("18-25","26-35", "36-45", "46-55", "56-65", "66-85"))
  )

manhattan_rides_df %>% 
  group_by(age_group) %>% 
  summarize(min = min(age), max = max(age), obs = n())
```

## Exporatory Data Analysis

```{r, Rides by day of week}
manhattan_rides_df %>% 
  group_by(day_of_week, year) %>% 
  summarize(obs = n()) %>% 
  ggplot(aes(x = day_of_week, y = obs, group = year, color = year)) +
  geom_point() + 
  geom_line()
```

Fewer rides during the week in 2020 (presumably because of WFH), but more rides on the weekends (presumably because people avoid subway/ ubers)

```{r, Rides per day summary}
manhattan_rides_df %>% 
  group_by(start_date, year) %>% 
  summarize(obs = n()) %>% 
  ggplot(aes(x = start_date, y = obs, group = year, color = year)) +
  geom_line() + 
  geom_smooth(se = FALSE)
```

Not that helpful, but not a meaningful difference in numbers of rides between 2019 and 2020 except maybe March/ April where there appears to be a slight dip


