---
title: lookup_table_stations
output: github_document
---

```{r, load required packages, include = FALSE}
library(tidyverse)
library(tidygeocoder)

knitr::opts_chunk$set(
  eval = FALSE, 
  message = FALSE, 
  warning = FALSE
)
```

```{r, read in CSV files and create df with all unique stations, message=FALSE, warning=FALSE}
file_names <- list.files(path = "./data")

find_unique_stations <- function(data_name){
  
  start_stations <-
    read_csv(str_c("./data/", data_name)) %>% 
    janitor::clean_names() %>% 
    select(c("start_station_id", "start_station_name", "start_station_latitude", "start_station_longitude")) %>%
    distinct() %>% 
    rename_all(~str_replace(.,"^start_station_","")) %>% 
    filter(id != "NULL") %>% 
    mutate(
      id = as.numeric(id)
    )
  
  end_stations <-
    read_csv(str_c("./data/", data_name)) %>% 
    janitor::clean_names() %>% 
    select(c("end_station_id", "end_station_name", "end_station_latitude", "end_station_longitude")) %>%
    distinct() %>% 
    rename_all(~str_replace(.,"^end_station_","")) %>% 
    filter(id != "NULL") %>% 
    mutate(
      id = as.numeric(id)
    )
  
  stations <- 
    bind_rows(start_stations, end_stations) %>% 
    distinct() %>% 
    arrange(id)
  
  return(stations)

}
```

