---
title: "membership"
output: html_document
---
```{r}
library(tidyverse)
library(viridis)
library(shiny)
library(timevis)
library(lubridate)
```

Input Citibike Membership Datafile
```{r}
membership_df = 
  read_csv("ridership.csv") %>%
  mutate(date = factor(date, ordered = TRUE, levels = c("01/2019", "02/2019", "03/2019", "04/2019",
                                                         "05/2019", "06/2019", "07/2019", "08/2019",
                                                         "09/2019", "10/2019", "11/2019", "12/2019",
                                                         "01/2020", "02/2020", "03/2020", "04/2020",
                                                         "05/2020", "06/2020", "07/2020", "08/2020",
                                                         "09/2020", "10/2020", "11/2020", "12/2020",
                                                         "01/2021", "02/2021", "03/2021", "04/2021",
                                                         "05/2021", "06/2021", "07/2021", "08/2021",
                                                         "09/2021", "10/2021"))) %>%
  rename(ct_annual_members = annual_members) %>%
  rename(ct_single_trip_passes = single_trip_passes) %>%
  rename(ct_single_day_passes = single_day_passes) %>%
  rename(ct_three_day_passes = three_day_passes) %>%
  rename(ct_total_annual_members = total_annual_members) %>%
  pivot_longer(
    cols = starts_with("ct"),
    names_to = "measure",
    values_to = "count"
  ) 

membership_df %>%
  ggplot(aes(x = date, y = count, group = measure), color = measure) +
  geom_line() +
  scale_fill_viridis_d(option = "C") +
  theme(axis.text.x = element_text(angle = 90, vjust = 0.5, hjust = 1))
```

Try to create Shiny Timeline

```{r}
ui <- fluidPage(
    
  titlePanel("CitiBike Membership Over Time"),
  
  sliderInput(
    inputId = "date",
    label = "Dates",
    min = as.Date("01/2019","%m/%Y"),
    max = as.Date("10/2021","%m/%Y"),
    value  = as.Date("01/2019","%m/%Y"),
    timeFormat = "%m/%Y",
    step = 1,
    animate = animationOptions(interval = 200, loop = FALSE)
  ),

  mainPanel(
    timevisOutput("timeline")
  )
)
    

server <- function(input, output){
    
    d = reactive({
      day = input$date
      
      d = membership_df 
    })
  
    output$nyc_map <- renderTimevis({

        timevis(membership_df)
    })
}

shinyApp(ui, server)
```

```{r}
timeline_1 <- data.frame(
  id      = 2:6,
  content = c("Annual Members", "Single Trip",
              "Single Day Pass", "Three Day Pass", "Total Annual Members")
)

timevis(timeline_1)
  
  ,
  start   = c("2016-01-10", "2016-01-11",
              "2016-01-20", "2016-02-14 15:00:00"),
  end     = c(NA, NA, "2016-02-04", NA)
)

timevis(data)
```

