---
title: "R Notebook"
output: github_notebook
---

```{r setup}
library(tidyverse)
library(lubridate)
library(shiny)
library(leaflet)
library(sf)
library(rgdal)
```

```{r load subway data}
turnstiles_2019 = read_csv("2019-turnstile.csv") %>% 
  mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))
  
  
turnstiles_2020 = read_csv("2020-turnstile.csv") %>% 
    mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))

turnstiles_19_20 = rbind(turnstiles_2019, turnstiles_2020) %>% 
  drop_na()  

# creating a cateogrical variable for exit data to make it more efficient to plot
turnstiles_19_20 = turnstiles_19_20 %>% 
  mutate(exists_cat = cut(exits, 
                          breaks = c(0, 2500, 5000, 10000, 20000, 40000, 60000, Inf), 
                          include.lowest = TRUE, 
                          ordered_result = TRUE))
```

```{r, load shapefile data}
subway_lines = st_read(
  "subway_lines_data/geo_export_cef610e7-3c97-412c-ac0a-44a37bcf4f9b.shp")

subway_lines = st_transform(subway_lines, CRS("+proj=longlat +ellps=GRS80 +datum=WGS84")) 
```

```{r}
# create color pallet 
beatCol = colorFactor(palette = 'RdYlGn', turnstiles_19_20$exists_cat)

# create labels 
labs = lapply(seq(nrow(turnstiles_19_20)), function(i) {
  paste0( '<p> Station Name: ', turnstiles_19_20[i, "stop_name"], '<p></p> Subway Lines: ', turnstiles_19_20[i, "daytime_routes"])
})
```


```{r practice map}
my_leaf = leaflet() %>%
  setView(-74.00, 40.78, zoom = 11) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addPolylines(data = subway_lines) 

fake = turnstiles_19_20 %>% filter(date == as.Date("2019-06-01","%Y-%m-%d"))
subway_map = leaflet(fake) %>% 
      addCircleMarkers(
        lat = ~ gtfs_latitude, 
        lng = ~ gtfs_longitude, 
        color = ~ beatCol(exists_cat),
        stroke = FALSE, 
        fillOpacity = 0.85,
        label = lapply(labs, htmltools::HTML)) %>% 
    leaflet::addLegend("bottomright", pal = beatCol, values = ~ exists_cat,
       title = "Ridership",
       opacity = 1)
```

```{r}
    leaflet(turnstiles_19_20_week) %>% 
      setView(-74.00, 40.78, zoom = 11) %>%
      addProviderTiles("CartoDB.Positron") %>% 
      addCircleMarkers(
        lat = ~ gtfs_latitude, 
        lng = ~ gtfs_longitude, 
        color = ~ colorpal(turnstile_count),
        stroke = FALSE, 
        fillOpacity = 0.85)
```


```{r, shiny UI}
ui <- fluidPage(
  
  titlePanel("Heatmap Manhattan Subway Ridership Overtime"),
  
  fluidRow
      sliderInput(inputId = "date", 
                  label = h3("Date Range"), 
                  min = as.Date("2019-01-01","%Y-%m-%d"),
                  max = as.Date("2020-12-25","%Y-%m-%d"),
                  value  = as.Date("2019-06-01","%Y-%m-%d"),
                  timeFormat = "%d %b %y",
                  step = 1,
                  animate = animationOptions(interval = 500, loop = FALSE),
                  ticks = F)
    )
  ),
  
  fluidRow(
    column(4, verbatimTextOutput("value"))
  ),
  
  mainPanel(
    leafletOutput("nyc_map", width = "70%", height = "750px")
  )
)

```

```{r SHINY server}
server <- function(input, output, session){
    
  #filtering data based on user input
  filtered_data = reactive({
      turnstiles_19_20 %>% 
        filter(date >= input$date) 
    })
  
  #creating base leaflet map
  output$nyc_map <- renderLeaflet({
      setView(-74.00, 40.78, zoom = 11) %>%
      addProviderTiles("CartoDB.Positron") %>% 
      addPolylines(data = subway_lines) 
  
  #creating base leaflet map
  output$nyc_map <- renderLeaflet({
      leaflet(filtered_data()) %>%
      addCircleMarkers(
        lat = ~ gtfs_latitude, 
        lng = ~ gtfs_longitude, 
        color = ~ pal(exits),
        stroke = FALSE, 
        fillOpacity = 0.85,
        label = lapply(labs, htmltools::HTML)) %>% 
    leaflet::addLegend("bottomright", pal = pal, values = ~ exits,
       title = "Ridership",
       opacity = 1)
  })

}
```

```{r}
my_leaf = leaflet(turnstiles_19_20) %>%
  setView(-74.00, 40.78, zoom = 11) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addPolylines(data = subway_lines) %>%
  addCircleMarkers(
    lat = ~ gtfs_latitude, 
    lng = ~ gtfs_longitude, 
    color = ~pal(exits),
    stroke = FALSE, 
    fillOpacity = 0.85,
    label = lapply(labs, htmltools::HTML)) %>% 
  addLegend("bottomright", pal = pal, values = ~exits,
    title = "Ridership",
    opacity = 1)
```


```{r}
shinyApp(ui, server)

library(rsconnect)
rsconnect::deployApp('./shiny_app.rmd')
```

