---
title: "subway_rides"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(lubridate)
library(shiny)
library(leaflet)
library(dplyr)
library(plotly)
library(ggplot2)
library(ggthemes)
library(gganimate)
library(maps)
library(dplyr)
```

```{r, ridership data for 2019 and 2020, Manhattan Only}
turnstiles_2019_m = read_csv("2019-turnstile.csv") %>% 
  filter(borough == "M") %>% 
  mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))
  
  
turnstiles_2020_m = read_csv("2019-turnstile.csv") %>% 
    filter(borough == "M") %>% 
    mutate(gtfs_latitude = as.numeric(gtfs_latitude),
         gtfs_longitude = as.numeric(gtfs_longitude))
```

ter = total estimated ridership
pc = percent change 

```{r, ridership data 3/1/2020 - today}
ridership_covid_changes = read_csv("covid-ridership.csv") %>% 
  janitor::clean_names() %>% 
  mutate(date = as.Date(date, "%m/%d/%Y")) %>% 
  rename(buses_ter = buses_total_estimated_ridership) %>% 
  rename(lirr_ter = lirr_total_estimated_ridership) %>% 
  rename(metro_north_ter = metro_north_total_estimated_ridership) %>% 
  rename(subways_ter = subways_total_estimated_ridership) %>% 
  rename(subways_pc = subways_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(metro_north_pc = metro_north_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(lirr_pc = lirr_percent_change_from_2019_monthly_weekday_saturday_sunday_average) %>% 
  rename(buses_pc = buses_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(bridges_and_tunnels_pc = bridges_and_tunnels_percent_change_from_pre_pandemic_equivalent_day) %>% 
  rename(access_a_ride_ter = access_a_ride_total_scheduled_trips) %>% 
  rename(access_a_ride_pc = access_a_ride_percent_change_from_pre_pandemic_equivalent_day)


ridership_covid_changes_2020 = ridership_covid_changes %>% 
  filter(date <= as.Date('2020-12-31'))

ridership_covid_pc_tidy = 
  ridership_covid_changes_2020 %>% 
  
  select(date, access_a_ride_pc, bridges_and_tunnels_pc, buses_pc, lirr_pc, metro_north_pc, subways_pc) %>% 
  
  pivot_longer(
    c(access_a_ride_pc:subways_pc), 
    names_to = "transit_system",
    values_to = "percent_change"
  ) %>% 
  
   mutate(transit_system = gsub("_pc", "", transit_system),
          percent_change = gsub("%", "", percent_change),
          percent_change = as.numeric(percent_change))
```

Ridership Line Plot 
2 ways (ggplot and ploty)
```{r, plotting ridership post COVID}
# Using ggplot
post_covid_transit = ridership_covid_pc_tidy %>% 
  ungroup() %>% 
  drop_na() %>% 
  ggplot(aes(x = date, y = percent_change, color = transit_system)) +
  geom_smooth(aes(color = transit_system))

ggplotly(post_covid_transit)

# Using plotly 
ridership_covid_pc_tidy %>% 
  ungroup() %>% 
  drop_na() %>% 
  plot_ly(
    x = ~date, 
    y = ~percent_change, 
    color = ~transit_system,
    type = "scatter",
    mode = "lines") %>% 
  layout(
    title = "Ridership Transit System Percent Change Following COVID",
    xaxis = list(title = "Date"),
    yaxis = list(title = "Percent Change")
  )

```








Practice Map 
```{r}
sample = turnstiles_2019_m %>% 
  filter(date == as.Date('2019-01-20'))

pal <- colorNumeric(palette = "Blues",
                    domain = sample$exits)

labs <- lapply(seq(nrow(sample)), function(i) {
  paste0( '<p> Station Name: ', sample[i, "stop_name"], '<p></p> Subway Lines: ', sample[i, "daytime_routes"])
})

my_leaf = leaflet(sample) %>%
  setView(-74.00, 40.78, zoom = 11) %>%
  addProviderTiles("CartoDB.Positron") %>% 
  addCircleMarkers(
    lat = ~ gtfs_latitude, 
    lng = ~ gtfs_longitude, 
    color = ~pal(exits),
    stroke = FALSE, 
    fillOpacity = 0.85,
    label = lapply(labs, htmltools::HTML)) %>% 
  addLegend("bottomright", pal = pal, values = ~exits,
    title = "2019 Ridership",
    opacity = 1)
```

Creating Map with Shiny Attempt Kinda Works 
```{r}
pal <- colorNumeric(palette = "Blues",
                    domain = turnstiles_2019_m$exits)
dateRange = 
  turnstiles_2019_m %>% 
  summarise(min = min(date), max = max(date)) %>% 
  as_vector() %>% 
  as_date()

ui <- fluidPage(
    
  titlePanel("Manhattan Subway Ridership Overtime"),
    
  sliderInput(inputId = "date", 
                label = "Date:",
                min = as.Date("2019-01-01","%Y-%m-%d"),
                max = as.Date("2019-12-31","%Y-%m-%d"),
                value = as.Date("2019-01-01"),
                timeFormat = "%Y-%m-%d"),
    leafletOutput("nyc_map")
)

server <- function(input, output){
    
    output$nyc_map <- renderLeaflet({

        leaflet(turnstiles_2019_m) %>%
        addProviderTiles("CartoDB.Positron") %>% 
        addCircleMarkers(
          lat = ~ gtfs_latitude, 
          lng = ~ gtfs_longitude, 
          color = ~pal(exits),
          stroke = FALSE, 
          fillOpacity = 0.85,
          label = lapply(labs, htmltools::HTML)) %>% 
        addLegend("bottomright", pal = pal, values = ~exits,
                  title = "2019 Ridership",
                 opacity = 1)
    })
}

shinyApp(ui, server)
```

GGPlot
```{r}
map = turnstiles_2019_m %>% 
  ggplot() +
  geom_point(aes(x = gtfs_longitude, y = gtfs_latitude, color = exits, size = exits), alpha = 0.5) + 
  transition_time(date) +
  labs(title = "Date: {frame_time}", color = "Ridership") +
  ease_aes("linear")

animate(map, duration = 10, fps = 20, width = 800, height = 800, renderer = gifski_renderer())
anim_save("map.gif")
```

Creating Map with Slider in Shiny
```{r}
pal <- colorNumeric(palette = "Blues",
                    domain = turnstiles_2019_m$exits)
dateRange = 
  turnstiles_2019_m %>% 
  summarise(min = min(date), max = max(date)) %>% 
  as_vector() %>% 
  as_date()

ui <- fluidPage(
    
  titlePanel(
    h1("Manhattan Subway Ridership Overtime", style = "padding-bottom: 20px")
    ),
    
  sidebarLayout(
    sidebarPanel(
      dateRangeInput(
        inputID = 'dateRange',
        label = "Date range:",
        start = dateRange[1], end = dateRange[1] %m+% years(1),
        min = dateRange[1], max = dateRange[2],
        separator = " to ", format = "dd/mm/yyyy",
        startview = 'month', weekstart = 1
      ),
      sliderInput(
        "animation",
        "Looping Date: ",
        min = dateRange[1], max = dateRange[2],
        value = dateRange[2], timeFormat = "%Y-%m-%d",
        animate = animationOptions(interval = 200, loop = FALSE)
      ),
    ),
    mainPanel(
      plotlyOutput(outputId = "nyc_map")
    )
  )
)


server <- function(input, output, session){
    
    observeEvent(input$dateRange, {
      updateSliderInput(
        session, "animation", 
        min = as_date(as.character(input$dateRange[1])),
        max = as_date(as.character(input$dateRange[2]))
      )
    })
  
    output$nyc_map <- renderPlotly({
        filterData = turnstiles_2019_m %>% 
          filter(
            between(
              date,
              as_date(as.character(input$dateRange[1])),
              as_date(as.character(input$dateRange[2]))
            )
          )
        
        
        leaflet(turnstiles_2019_m) %>%
        addProviderTiles("CartoDB.Positron") %>% 
        addCircleMarkers(
          lat = ~ gtfs_latitude, 
          lng = ~ gtfs_longitude, 
          color = ~pal(exits),
          stroke = FALSE, 
          fillOpacity = 0.85,
          label = lapply(labs, htmltools::HTML)) %>% 
        addLegend("bottomright", pal = pal, values = ~exits,
                  title = "2019 Ridership",
                 opacity = 1)
    })
}

shinyApp(ui, server)
```

